-- --------------------------------------------------------
--
-- Ported to PostgreSQL by Ray O'Donnell <ray@teladesign.ie>
-- September 2018
--
-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `count`
--

-- This table doesn't seem to be used anywhere.

-- CREATE TABLE IF NOT EXISTS `count` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `type` int(11) NOT NULL,
--   `count` int(11) NOT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `type` (`type`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `countgreen`
--

-- This table doesn't seem to be used anywhere.

-- CREATE TABLE IF NOT EXISTS `countgreen` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `type` int(11) NOT NULL,
--   `count` int(11) NOT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `type` (`type`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------


begin;


--
-- Tabelstructuur voor tabel `fosdem`
--

create table if not exists fosdem (
  id bigint not null generated by default as identity,
  fid bigint not null,
  fgroup bigint not null,
  fcount bigint not null,

  constraint fosdem_pk primary key (id)
);

grant select, insert, update, delete on fosdem to fosdem_temp;


-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `fosdem_alive`
--

create table if not exists fosdem_alive (
  id bigint not null generated by default as identity,
  ip text,
  posid text default null,
  boundid text,
  timepos text,

  constraint fosdem_alive_pk primary key (id)
);

alter table fosdem_alive alter column id restart with 2;

grant select, insert, update, delete on fosdem_alive to fosdem_temp;


-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `fosdem_logger`
--

create table if not exists fosdem_logger (
  id bigint not null generated by default as identity,
  fid bigint not null,
  fgroup bigint not null,
  fdate text not null,
  faction text not null,
  room text not null,

  constraint fosdem_logger_pk primary key (id)
);

grant select, insert, update, delete on fosdem_logger to fosdem_temp;


-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `fosdem_print`
--

create table if not exists fosdem_print (
  id bigint not null generated by default as identity,
  printid text not null,
  printtype text not null,
  printvalue text not null,
  status bigint not null,
  print text not null,
  print2 text not null,
  eventid bigint not null,

  constraint fosdem_print_pk primary key (id)
);

grant select, insert, update, delete on fosdem_print to fosdem_temp;


-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `fosdem_settings`
--

create table if not exists fosdem_settings (
  id bigint not null generated by default as identity,
  fgroup bigint not null,
  state bigint not null,

  constraint fosdem_settings_pk primary key (id)
);

grant select, insert, update, delete on fosdem_settings to fosdem_temp;


-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `users`
--

create table if not exists users (
  user_id bigint not null generated by default as identity,
  user_name text not null,
  user_password_hash text not null,
  user_email text not null,

  constraint users_pk primary key (user_id),
  constraint users_unique_name unique (user_name),
  constraint users_unique_email unique (user_email)
);

alter table users alter column user_id restart with 2;

comment on column users.user_id is 'Auto-incrementing user_id of each user; unique index.';
comment on column users.user_name is 'User''s name; unique.';
comment on column users.user_password_hash is 'User''s password in salted and hashed format.';
comment on column users.user_email is 'User''s email: unique.';

grant select, insert, update, delete on users to fosdem_temp;


-- --------------------------------------------------------

commit;

-- --------------------------------------------------------
-- End.
-- --------------------------------------------------------

